### ISSUE TITLE
Inventory of WES-specific code

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca-wes#1]
This is a meta issues that should be used as a basis to spawn other, more bite-sized issues. The idea is to create a list of code pieces (modules/classes/functions) that should be added to FOCA-WES over time from [cwl-WES](https://github.com/elixir-cloud-aai/cwl-WES). After agreeing on an initial set of code pieces (we might add more later), a specific issue for adding each of these code pieces should then be added and individually resolved. Each added code piece should come with its own unit tests ( (code coverage should generally be 100%, possibly with few exceptions) and documentation. All code should adhere to the [contributing guidelines](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/contributing_guidelines.md), including those [specific to Python](https://github.com/elixir-cloud-aai/elixir-cloud-aai/blob/dev/resources/python.md). Note also that along the way, we might generalize existing cwl-WES code or refactor it to improve the existing implementation. These aspects will be discussed in the individual issues.

For compiling the list of code pieces to be added, note that the repository should contain all code that is:

- not already in [FOCA](https://github.com/elixir-cloud-aai/foca) (because it is general to _any_ microservice)
- general to WES
- not specific to any _individual_ WES implementation (i.e., any code that relies on a specific workflow engine)

The best way to go about this is probably to:

- look through the [cwl-WES](https://github.com/elixir-cloud-aai/cwl-WES) codebase and compile an inventory of all modules
- remove from these any modules with functionality that is already completely captured in FOCA
- remove from these any modules with functionality that is entirely specific to `cwl-tes` (call to `cwl-tes`, log parsing etc)
- look through remaining modules and repeat the above on the class/function level

The [FOCA](https://github.com/elixir-cloud-aai/foca) repository can be used as an example of how to go about implementing FOCA-WES, as it is very similar. There is a [similar meta issue](https://github.com/elixir-cloud-aai/foca/issues/5) as well, although it mostly stays on the module level. Possibly we need to do this a bit more fine-grained for this repo, as several modules will contain both generic and specific WES code.

**Comment by bearkruz** [comment]
Cheers, Alex!

Below I have listed out a contrast between cwl-WES and FOCA's modules. With a tick means the cwl-WES module functionality is accounted for in FOCA. 

## Remarks: 
- In the FOCA sample app, the user uploads their own YAML config file. If this is the same for FOCA-WES, does this mean that cwl-WES's 'Config/App_config.yaml' and 'Config/Log_config.yaml' are not needed in FOCA-WES? 
- It appears as if almost all the needed code for FOCA-WES will come from the GA4GH folder. Here, all but one file ("run_workflow.py") is free of CWL specific code. 
- It is unclear whether 'Tasks/Celery_task_monitor.py' and 'Tasks/Register_celery.py ' are fully accounted for within the celery functionality of FOCA. Can you comment on this?

## File comparison: 

**API**
- [x] 20181010.be85140.workflow_execution_service.swagger.yaml (*version 0.3*; outdated)
- [ ] 20180830.74fd916.workflow_execution_service.swagger.yaml (*version 1.0*)
- [x] register_openapi.py

**CONFIG**
- [x] App_config.py
- [ ] App_conifg.yaml (*FOCA-WES: supplied by user as `config.yaml` to be registered by FOCA)
- [ ] Log_config.yaml (merged into FOCA's `config.yaml`)

**DATABASE**
- [x] DB_utils.py
- [x] Register_mongoDB.py

**ERRORS**
- [x] Errors.py (*In FOCA as exceptions.py*)

**FACTORIES**
- [x] Celery_app.py
- [x] Connexion_app.py

**GA4GH**
- [ ] Server.py
- [ ] States.py
- [ ] Endpoints/Cancel_run.py
- [ ] Endpoints/Get_run_log.py
- [ ] Endpoints/Get_run_status.py
- [ ] Endpoints/Get_service_info.py
- [ ] Endpoints/List_runs.py
- [ ] Endpoints/run_workflow.py (*NOTE: A lot of CWL specific code here*)

**SECURITY**
- [x] Cors.py
- [x] Decorators.py (*in FOCA as auth.py*)


**TASKS**
- [ ] Celery_task_monitor.py  (*Might be accounted for in FOCA*)
- [x] Register_celery.py
- [ ] Utils.py
- [ ] Tasks/cancel.run.py
- [ ] Tasks/run_workflow.py

**Comment by uniqueg** [comment]
Thanks a lot @bearkruz, this is great. Edited very slightly in a few places. As we can see, we will need the specs, all of the code in the `ga4gh` folder that isn't CWL-specific, and most of the code in the `tasks` folder.

The latter we will do last, because it will need some refactoring. The task monitor is not such a good idea as it presents a bottleneck for scalability. There is also some more code in a cwl-WES branch that I still have to complete and merge, it's quite a big change.

But for now we can go ahead with the relatively simple stuff, starting with writing a basic FOCA-compatible `config.yaml` file (that we can extend when adding further functionality) and adding the WES specs. Perhaps you could create an issue for that.

**Comment by bearkruz** [comment]
Cheers for those updates, Alex! 

I've gone ahead and created **_'Add Config File'_** as a new issue here: #2
